### ISSUE TITLE
Https?

### ISSUE THREAD

**Issue by Kylart** [mathieutu/vue-cli-plugin-express#16]
Hello,

Is it possible to setup this plugin on a https setup? If so, would you have an example?

Thank you! 😄

**Comment by mathieutu** [comment]
Sorry, I'm seeing that just now.
Actually no, I'm sorry but https isn't handled directly in the server for now. 
I would accept a PR for that.

**Comment by acerspyro** [comment]
@Kylart Personally, I simply run the application as HTTP on a non-standard port, and then proxy/reverse proxy it through NGINX (which can be done in Docker) to get HTTPS support.

Here's how I've set up my reverse proxy in NGINX

```nginx
server {

    server_name domainname.tld;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        client_max_body_size 10M;

        proxy_pass http://domainname.tld:8080;  # no trailing slash, assuming you're running vue on port 8080
        proxy_redirect off;

        # Socket.IO Support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }


    listen 80;
}
```

Make sure to specify your ``host`` parameter in your ``vue.config.js``
```js
module.exports = {
  devServer: {
      host: 'domainname.tld'
  }
}
```

You can then use Certbot or proceed with your SSL configuration as usual.

**Comment by Kylart** [comment]
I ended up with this structure  which seems to be a widely good practice.

I just though that it would be a good thing to have that https support but I might be wrong since nginx / docker combination is a super strong setup.
