### ISSUE TITLE
Precedence selection: Allow configuring for Express routes to fallback to Vue routes

### ISSUE THREAD

**Issue by acerspyro** [mathieutu/vue-cli-plugin-express#25]
As it is, the only way to use this plug-in is to have Vue configured to fallback to Express on fail, which doesn't work when a 404 page is set up in Vue.

It would be nice to be able to make Express take precedence, and fallback to Vue if the route isn't found.

**Comment by mathieutu** [comment]
Actually, it's the opposite! 😅

Express serve vue at the end of routes declaration, and so, vue is a fallback.

However only for development purpose we use the webpack-dev-server proxy, to redirect to the nodejs server the calls which didn't reach.  It allows us to keep the native "serve" command.

If you have a better idea to make consistent this behavior, I'm open to discuss that.

**Comment by acerspyro** [comment]
Ah yes, that's correct. I should probably spend more time wording out issues lol.

During development, I found that the 404 page assignment using vue-router was taking over all Express routes. Every call to the underlying Express server resulted in a 404, so I had to disable the 404 page when NODE_ENV is in development mode.
