### ISSUE TITLE
I cannot run both VUE and EXPRESS

### ISSUE THREAD

**Issue by michaelsogos** [mathieutu/vue-cli-plugin-express#29]
Hi @mathieutu ,

Probably i made something wrong, but just following your example it doesn't work.
I mean, after created my VUE APP and executed "vue add express" later, i just copied the GET route /foo; then i typed "yarn express" and next i typed "yarn serve".
The browser show the vue page at http://localhost:8080, but at http://localhost:8080/foo i expect to see the json example, but instead i continue to see the VUE page.

What i miss 😄 ?

**Comment by mathieutu** [comment]
Hi, 
The `yarn express` command should not stop. This is a dev server that should run in parallel of `yarn serve`.

When you run `yarn express` you should see an url where the server is launched. By default it's on port 3000 I think.

However all calls from vuejs to the server routes are proxified, so you can use :
`axios.get('/foo')` in your code.

If you want to clarify that behaviour on the readme, please feel free to open a pull request.

(PS: I will be in holliday on the road from now, so I will not be able to see your answer before september)

**Comment by michaelsogos** [comment]
Thanks @mathieutu 

I run both, and as you said express run on 3000 and vue app on 8080.
But if i navigate to localhost:8080/ i can see properly vue pages, but at the same time in postman if i GET localhost:8080/foo it not works.
Should i not exptect this because the proxy is handled internally by the vue app (like axios example)? so i should i test on port 3000 in postman?

Have nice holidays 😄

**Comment by mathieutu** [comment]
Exactly. You have to test it on 3000 on postman.

I let you see the doc about proxied calls in Vuejs: https://cli.vuejs.org/config/#devserver-proxy
(applied [here](https://github.com/mathieutu/vue-cli-plugin-express/blob/master/src/servicePlugin/webpackConfig.js) in this project)
