### ISSUE TITLE
shouldServeApp is true, but it doesn't serve my app.

### ISSUE THREAD

**Issue by Krummelz** [mathieutu/vue-cli-plugin-express#31]
I created a quick project, added this plugin with `vue add express`, and then ran `yarn express`. When I browse to localhost:3000 it shows only an error saying "Cannot GET /".

I can uncomment some of the code in the ./srv/index.js to add an API route, and that works fine. But it still doesn't serve my Vue app. What am I missing?

**Comment by ionutvladu** [comment]
I have same issue

**Comment by mathieutu** [comment]
Please read the [Usage](https://github.com/mathieutu/vue-cli-plugin-express#usage) section of the documentation.

You have to start the vuejs dev server with `yarn serve`

It will serve your app only in [production mode](https://github.com/mathieutu/vue-cli-plugin-express#use-your-app-in-production).
