### ISSUE TITLE
API not working in PROD?

### ISSUE THREAD

**Issue by adelriosantiago** [mathieutu/vue-cli-plugin-express#33]
I don't know if I am doing something wrong. I have installed the plugin and uncommented `/foo` route so that it replies with `{msg: 'foo'}`. It works great in dev. If I go to "localhost:3000/foo" I will get `msg` and in the app (running at 8080) if I do `axios.get("/foo")` I also get `msg` as well.

However I can't get the same results in PROD. I `npm run build` then served the "dist" folder with `serve -s dist`. Doing `localhost:5000/foo` (`serve` serves on 5000 by default), `localhost:5000/#/foo` or `axios.get("/foo")` inside the app doesn't work at all.

How can I fix this?

**Comment by mathieutu** [comment]
Hi,
To serve your app in production you have to use the `yarn express:run`command.

See the documentation: 
https://github.com/mathieutu/vue-cli-plugin-express#use-your-app-in-production
