### ISSUE TITLE
Handling async initialization for express app

### ISSUE THREAD

**Issue by arunkoshi** [mathieutu/vue-cli-plugin-express#44]
We have a module which needs async initialization before using it. What would be the best way to handle the initialization?

I believe this is where the exported code from index.js is invoked - [server(app, http)](https://github.com/mathieutu/vue-cli-plugin-express/blob/master/src/server.js#L25)

Could there be any issues setting up the _app_ asynchronously? Is there a way to introduce await here?

_index.js_
`
export default (app) => {
 someThirdPartyModule.initialize().then(_ => setupRoutes(app))
}
`

**Comment by mathieutu** [comment]
Hi, 
To be sure I'm understanding well, could you give me a code example of what you're trying to do, and the before/after of what you need?

Thanks.

**Comment by mathieutu** [comment]
Would you be happy with something like that?

```js
export async default (app) => { 
	await someThirdPartyModule.initialize()
	setupRoutes(app)) 
}
```

If so, i would accept a PR if you want to do it.

**Comment by arunkoshi** [comment]
Thanks for your response @mathieutu  

Yes that would be ideal. I will try to submit a PR when i have free cycles. 

However, more immediately, i wanted to know, with what is available today, if we did an async initialization like 
```
export async default (app) => { 
	someThirdPartyModule.initialize().then(_ => setupRoutes(app))
}
```

Would that cause any issues? 

I noticed that since the routes are getting setup after the async initialization, the plugin is unable to report the registered routes. It prints a message  `No api routes found (yet?).` 

However other than that, are there any serious concerns having the routes setup delayed by the initialization?

**Comment by mathieutu** [comment]
I actually don't see any issue with that.
The best way to be sure is to try!

**Comment by mathieutu** [comment]
Hi @arunkoshi.
Is it working the way you want? Can we close this issue?

Thanks.

**Comment by arunkoshi** [comment]
Yes. It is.
