### ISSUE TITLE
socket.io support

### ISSUE THREAD

**Issue by hsun-cnnxty** [mathieutu/vue-cli-plugin-express#8]
Possible to allow support of socket.io by exposing the return value from app.listen(..) to application code?

**Comment by mathieutu** [comment]
Yeah, I can be a good idea.
I don't know yet how we could handle that, but I would accept a Pull Request for it.

**Comment by hsun-cnnxty** [comment]
Submitted PR #10

**Comment by mathieutu** [comment]
And released [🔖v1.0.0](https://github.com/mathieutu/vue-cli-plugin-express/releases/tag/v1.0.0).

Thanks for your help!  😉
